#!/bin/sh

###
### GPIO pin get & set for Hermes-BBB from Twisted Pear Audio
###

# LED1
test "$1" = 0 -o "$1" = 1 && echo "$1" > /sys/class/gpio/gpio30/value

# LED2
test "$2" = 0 -o "$2" = 1 && echo "$2" > /sys/class/gpio/gpio60/value

# LED3
test "$3" = 0 -o "$3" = 1 && echo "$3" > /sys/class/gpio/gpio31/value

# Button1
cat /sys/class/gpio/gpio51/value

# Button2
cat /sys/class/gpio/gpio48/value

# Button3
cat /sys/class/gpio/gpio49/value

